//! Embeds the built panel bundle into the binary.
//!
//! The panel ships as one self-contained binary, so the compiled single-page
//! application is turned into a static asset table at build time. The table is
//! generated rather than hand-written because the bundler emits content-hashed
//! file names that change on every UI change.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// Directory holding the built bundle, relative to the crate root.
const BUNDLE_DIR: &str = "panel-ui/dist";

/// Largest single asset embedded. A larger file is a packaging mistake, and
/// silently baking it into the binary would hide that.
const MAX_ASSET_BYTES: u64 = 16 * 1024 * 1024;

fn main() {
    let crate_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let bundle = crate_dir.join(BUNDLE_DIR);
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", bundle.display());

    let mut entries = Vec::new();
    if bundle.is_dir() {
        collect(&bundle, &bundle, &mut entries);
        entries.sort_by(|left, right| left.0.cmp(&right.0));
    }

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs. Do not edit.\n");
    writeln!(
        generated,
        "pub(crate) static PANEL_ASSETS: &[(&str, &str, &[u8])] = &["
    )
    .expect("write");
    for (route, path) in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
        writeln!(
            generated,
            "    ({:?}, {:?}, include_bytes!({:?})),",
            route,
            content_type(route),
            path
        )
        .expect("write");
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("out dir")).join("panel_assets.rs");
    std::fs::write(&out, generated).expect("write generated panel asset table");
}

/// Walks the bundle directory, collecting route/path pairs.
fn collect(root: &Path, directory: &Path, entries: &mut Vec<(String, PathBuf)>) {
    let Ok(listing) = std::fs::read_dir(directory) else {
        return;
    };
    for entry in listing.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, entries);
            continue;
        }
        let Ok(metadata) = entry.metadata() else {
            continue;
        };
        if metadata.len() > MAX_ASSET_BYTES {
            panic!(
                "panel asset {} is larger than {MAX_ASSET_BYTES} bytes",
                path.display()
            );
        }
        let Ok(relative) = path.strip_prefix(root) else {
            continue;
        };
        let route = relative
            .components()
            .map(|component| component.as_os_str().to_string_lossy().into_owned())
            .collect::<Vec<_>>()
            .join("/");
        entries.push((route, path));
    }
}

/// Maps a file extension onto the media type the panel serves it with.
fn content_type(route: &str) -> &'static str {
    match route.rsplit('.').next().unwrap_or_default() {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" => "application/json; charset=utf-8",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "webp" => "image/webp",
        "ico" => "image/x-icon",
        "woff2" => "font/woff2",
        "woff" => "font/woff",
        "ttf" => "font/ttf",
        "map" => "application/json; charset=utf-8",
        "txt" => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}
