// Regenerates src/schema.js from telemt's own strict-key tables.
//
// The assistant's worst failure mode is inventing a configuration key that
// looks plausible. Grounding it in the list the proxy actually validates
// against removes the guesswork, and generating that list rather than typing it
// means a key added to telemt cannot silently go missing here.
//
//   node tools/generate-schema.mjs          # write src/schema.js
//   node tools/generate-schema.mjs --check  # fail if it is out of date

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, "..", "..");
const sources = [
  "src/config/load/strict_keys.rs",
  "src/config/load/strict_keys/fork.rs",
];

/** Pulls every `const NAME_CONFIG_KEYS: &[&str] = &[ "a", "b" ];` table. */
function extractTables(rust) {
  const tables = {};
  const pattern = /const (\w+_CONFIG_KEYS): &\[&str\] = &\[(.*?)\];/gs;
  for (const match of rust.matchAll(pattern)) {
    tables[match[1]] = [...match[2].matchAll(/"([^"]+)"/g)].map((m) => m[1]);
  }
  return tables;
}

const tables = {};
for (const relative of sources) {
  const absolute = path.join(repoRoot, relative);
  if (!fs.existsSync(absolute)) continue;
  Object.assign(tables, extractTables(fs.readFileSync(absolute, "utf8")));
}

if (Object.keys(tables).length === 0) {
  console.error(
    "No key tables found. Run this from a checkout of the telemt repository.",
  );
  process.exit(1);
}

// Only the tables an operator writes by hand are worth shipping; the internal
// suggestion helpers are not part of the configuration surface.
const wanted = [
  ["TOP_LEVEL_CONFIG_KEYS", "top-level"],
  ["GENERAL_CONFIG_KEYS", "[general]"],
  ["PROXY_MODES_CONFIG_KEYS", "[general.modes]"],
  ["LINKS_CONFIG_KEYS", "[general.links]"],
  ["TELEMETRY_CONFIG_KEYS", "[general.telemetry]"],
  ["LOGGING_CONFIG_KEYS", "[logging]"],
  ["NETWORK_CONFIG_KEYS", "[network]"],
  ["SERVER_CONFIG_KEYS", "[server]"],
  ["API_CONFIG_KEYS", "[server.api]"],
  ["CONNTRACK_CONTROL_CONFIG_KEYS", "[server.conntrack_control]"],
  ["LISTENER_CONFIG_KEYS", "[[server.listeners]]"],
  ["TIMEOUTS_CONFIG_KEYS", "[timeouts]"],
  ["CENSORSHIP_CONFIG_KEYS", "[censorship]"],
  ["TLS_FETCH_CONFIG_KEYS", "[censorship.tls_fetch]"],
  ["ACCESS_CONFIG_KEYS", "[access]"],
  ["RATE_LIMIT_BPS_CONFIG_KEYS", "[access.user_rate_limits.<user>]"],
  ["UPSTREAM_CONFIG_KEYS", "[[upstreams]]"],
  ["WEB_CONFIG_KEYS", "[web]"],
  ["WEB_LIMITS_CONFIG_KEYS", "[web.limits]"],
  ["WEB_TIMEOUTS_CONFIG_KEYS", "[web.timeouts]"],
  ["WEB_DEBUG_CONFIG_KEYS", "[web.debug]"],
  ["WEB_VHOST_CONFIG_KEYS", "[[web.vhosts]]"],
  ["WEB_DECOY_CONFIG_KEYS", "[[web.vhosts]].decoy"],
  ["WEB_PROFILE_CONFIG_KEYS", "[[web.vhosts]].profiles"],
  ["FORK_CONFIG_KEYS", "[fork]"],
  ["FORK_RUNTIME_CONFIG_KEYS", "[fork.runtime]"],
  ["FORK_WEB_CONFIG_KEYS", "[fork.web]"],
  ["FORK_WEB_LIMITS_CONFIG_KEYS", "[fork.web.limits]"],
  ["FORK_WEB_TIMEOUTS_CONFIG_KEYS", "[fork.web.timeouts]"],
  ["FORK_WEB_PROFILE_LIMITS_CONFIG_KEYS", "[[fork.web.profiles]].limits"],
  ["FORK_PROMETHEUS_CONFIG_KEYS", "[fork.prometheus]"],
  ["FORK_TELEGRAM_CONFIG_KEYS", "[fork.telegram]"],
  ["PANEL_CONFIG_KEYS", "[panel]"],
  ["PANEL_TLS_CONFIG_KEYS", "[panel.tls]"],
  ["PANEL_CLUSTER_CONFIG_KEYS", "[panel.cluster]"],
];

const sections = [];
for (const [table, section] of wanted) {
  const keys = tables[table];
  if (!keys) {
    console.error(`Missing table ${table}; strict_keys.rs was restructured.`);
    process.exit(1);
  }
  sections.push({ section, keys });
}

const generated =
  `// Generated by tools/generate-schema.mjs from telemt's strict-key tables.\n` +
  `// Do not edit by hand; run \`node tools/generate-schema.mjs\` instead.\n\n` +
  `export const CONFIG_SECTIONS = ${JSON.stringify(sections, null, 2)};\n\n` +
  `/** Every configuration key telemt accepts, as one flat set. */\n` +
  `export const KNOWN_KEYS = new Set(\n` +
  `  CONFIG_SECTIONS.flatMap((entry) => entry.keys),\n` +
  `);\n\n` +
  `/** The key inventory rendered for a system prompt. */\n` +
  `export function renderSchema() {\n` +
  `  return CONFIG_SECTIONS.map(\n` +
  `    (entry) => \`\${entry.section}: \${entry.keys.join(", ")}\`,\n` +
  `  ).join("\\n");\n` +
  `}\n`;

const target = path.join(here, "..", "src", "schema.js");

if (process.argv.includes("--check")) {
  const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
  if (current !== generated) {
    console.error(
      "src/schema.js is out of date. Run: node tools/generate-schema.mjs",
    );
    process.exit(1);
  }
  console.log(`src/schema.js is current (${sections.length} sections).`);
} else {
  fs.writeFileSync(target, generated);
  const total = sections.reduce((sum, entry) => sum + entry.keys.length, 0);
  console.log(`src/schema.js written: ${sections.length} sections, ${total} keys.`);
}
